USE [DoctorAppointmentManagement];
CREATE TABLE PERSON
(
    personID INT NOT NULL IDENTITY(1, 1),
    fName NVARCHAR(255) NOT NULL,
    lName NVARCHAR(255) NOT NULL,
	SSN NCHAR(11) NOT NULL,
    DOB DATE NOT NULL,
    phoneNum NCHAR(12) NOT NULL,
    emailAddress NVARCHAR(255) NOT NULL,
    PRIMARY KEY (personID)
);

CREATE TABLE DOCTOR
(
	doctorID INT UNIQUE NOT NULL,
	licenseID int NOT NULL,
	specialty NVARCHAR(255) NOT NULL
	FOREIGN KEY (doctorID) REFERENCES PERSON(personID));

CREATE TABLE PATIENT (
	patientID INT UNIQUE NOT NULL,
	weight FLOAT NOT NULL,
	height FLOAT NOT NULL,
	bloodType NVARCHAR(5) NOT NULL,
	insuranceCompany NVARCHAR(30) NOT NULL,
	FOREIGN KEY (patientID) REFERENCES PERSON(personID)
);

CREATE TABLE APPOINTMENT (
	appointmentID INT NOT NULL IDENTITY(1,1),
	apptStatus NVARCHAR(30) NOT NULL,
	apptStartDateTime DATETIME NOT NULL,
	apptEndDateTime DATETIME NOT NULL,
	roomNum INT NOT NULL,
	visitReason NVARCHAR(255) NOT NULL,
	patientID INT NOT NULL,
	doctorID INT NOT NULL,
	FOREIGN KEY (patientID) REFERENCES PATIENT(patientID),
	FOREIGN KEY (doctorID) REFERENCES DOCTOR(doctorID)
);